name: Terraform Apply

on:
  workflow_run:
    workflows: [test.yml]
    types:
      - completed


jobs:
  apply:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'


      - name: Dump workflow context
        run: echo '${{ toJson(github.event.workflow_run) }}'
