name: build

on:
  workflow_call:
    inputs:
      aws-region:
        default: ap-southeast-2
        required: false
        type: string
      branch-sha:
        required: false
        type: string
      image-name:
        required: true
        type: string
      role-to-assume:
        required: true
        type: string
      version:
        required: true
        type: string


jobs:
  image_build:
    permissions:
      contents: read  # This is required for actions/checkout
      id-token: write  # This is required for requesting the JWT
      packages: write  # required to publish to github

    runs-on: ${{ vars.ORG_DEFAULT_RUNNER_OS }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.role-to-assume }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: Dockerfile
          platforms: linux/amd64
          provenance: false
          push: true
          tags: |
            ghcr.io/televate-au/${{ inputs.image-name }}:${{ inputs.version }}-${{ inputs.branch-sha }}
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.image-name }}_nonprod:${{ inputs.version }}-${{ inputs.branch-sha }}
