name: Lint Terraform

on:
  workflow_call:

env:
  TF_IN_AUTOMATION: 1
  TF_INPUT: 0


jobs:
  terraform_fmt_and_validate:
    runs-on: ${{ vars.ORG_DEFAULT_RUNNER_OS }}
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -recursive .

    - name: Terraform Init
      run: terraform init -backend=false

    - name: Terraform Validate
      run: terraform validate
