on:
  pull_request:
  workflow_dispatch:

permissions: write-all


jobs:
  job:
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      run: echo '${{ toJSON(github) }}'

    - name: Install OIDC Client from Core Package
      run: npm install @actions/core@1.6.0 @actions/http-client
    - name: Get Id Token
      uses: actions/github-script@v6
      id: idtoken
      with:
        script: |
          const coredemo = require('@actions/core')
          let id_token = await coredemo.getIDToken()
          coredemo.setOutput('id_token', id_token)


    - name: debug
      run: echo ${{ steps.idtoken.outputs.id_token }} | base64
