name: Tag updated modules

on:
  push:
    # branches: [master]


jobs:
  get_changes:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed modules and build matrix
        id: set_matrix
        run: |
          folders=$(git diff --name-only HEAD HEAD~ | xargs -L1 dirname | sort | uniq | grep -v '\.')
          echo "matrix=$(jq -s -R -rc 'split("\n") | .[:-1]' <<< $folders)"  >> $GITHUB_OUTPUT

  tag:
    needs: get_changes
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        folder: ${{ fromJson(needs.get_changes.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v3

      - name: Get version from file
        id: version
        run: |
          echo "version=$(head -n1 ${{ matrix.folder }}/.version)" >> $GITHUB_OUTPUT

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ matrix.folder }}-${{ steps.version.outputs.version }}
