name: Tag updated modules

on:
  push:
    # branches: [master]


jobs:
  get_changes:
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed modules and build matrix
        id: set_matrix
        run: |
          git diff --name-only HEAD HEAD~
          folders=$(git diff --name-only HEAD HEAD~ | xargs -L1 dirname | sort | uniq | grep -v '\.')
          echo "matrix=$(jq -s -R -rc 'split("\n") | .[:-1]' <<< $folders)"
