name: Test

on:
  workflow_call:
    secrets:
      CICD_PAT:
        required: true

env:
  PY_COLORS: 1
  FORCE_COLOR: 1


jobs:
  test:
    runs-on: ${{ vars.ORG_DEFAULT_RUNNER_OS }}
    strategy:
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - name: Install requirements
        run: |
          git config --global url."https://${{ secrets.CICD_PAT }}@github".insteadOf ssh://git@github
          pip install -r requirements.txt

      - name: Lint code
        run: tox -e black,lint

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # TODO - dynamically fetch containers
      - name: Fetch containers
        run: |
          docker pull localstack/localstack:latest
          docker pull redis:latest
          docker pull ghcr.io/televate-au/asterisk_event_ingestion:latest

      - name: Run Tests
        # Run tox using the version of Python in `PATH`
        run: tox -e clean,py,report
